default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: koi8rus

development:
  <<: *default
  database: users-api_develop_db

test:
  <<: *default
  database: users-api_test

production:
  <<: *default
  database: users-api_db
